# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout.addWidget(self.open_button)
        self.save_as_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_as_button.setObjectName("save_as_button")
        self.horizontalLayout.addWidget(self.save_as_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.record_button = QtWidgets.QPushButton(self.centralwidget)
        self.record_button.setObjectName("record_button")
        self.horizontalLayout.addWidget(self.record_button)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.revert_button = QtWidgets.QPushButton(self.centralwidget)
        self.revert_button.setObjectName("revert_button")
        self.horizontalLayout.addWidget(self.revert_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_2.addWidget(self.play_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.language_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.language_comboBox.setObjectName("language_comboBox")
        self.language_comboBox.addItem("")
        self.language_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.language_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.male_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.male_radioButton.setChecked(True)
        self.male_radioButton.setObjectName("male_radioButton")
        self.horizontalLayout_9.addWidget(self.male_radioButton)
        self.female_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.female_radioButton.setObjectName("female_radioButton")
        self.horizontalLayout_9.addWidget(self.female_radioButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.variant_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.variant_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.variant_comboBox.setObjectName("variant_comboBox")
        self.horizontalLayout_4.addWidget(self.variant_comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.pitch_slider = QtWidgets.QSlider(self.centralwidget)
        self.pitch_slider.setTracking(False)
        self.pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.pitch_slider.setObjectName("pitch_slider")
        self.horizontalLayout_5.addWidget(self.pitch_slider)
        self.pitch_lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.pitch_lcdNumber.setObjectName("pitch_lcdNumber")
        self.horizontalLayout_5.addWidget(self.pitch_lcdNumber)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setTracking(False)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_6.addWidget(self.volume_slider)
        self.volume_lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.volume_lcdNumber.setObjectName("volume_lcdNumber")
        self.horizontalLayout_6.addWidget(self.volume_lcdNumber)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.speed_slider = QtWidgets.QSlider(self.centralwidget)
        self.speed_slider.setTracking(False)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.horizontalLayout_7.addWidget(self.speed_slider)
        self.speed_lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.speed_lcdNumber.setObjectName("speed_lcdNumber")
        self.horizontalLayout_7.addWidget(self.speed_lcdNumber)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.delay_slider = QtWidgets.QSlider(self.centralwidget)
        self.delay_slider.setTracking(False)
        self.delay_slider.setOrientation(QtCore.Qt.Horizontal)
        self.delay_slider.setTickInterval(1)
        self.delay_slider.setObjectName("delay_slider")
        self.horizontalLayout_8.addWidget(self.delay_slider)
        self.delay_lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.delay_lcdNumber.setObjectName("delay_lcdNumber")
        self.horizontalLayout_8.addWidget(self.delay_lcdNumber)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionRecord = QtWidgets.QAction(MainWindow)
        self.actionRecord.setObjectName("actionRecord")
        self.actionRevert = QtWidgets.QAction(MainWindow)
        self.actionRevert.setObjectName("actionRevert")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionPlay)
        self.menuEdit.addAction(self.actionStop)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRecord)
        self.menuEdit.addAction(self.actionRevert)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_("espeak-qtgui"))
        self.new_button.setText(_("New"))
        self.open_button.setText(_("Open"))
        self.save_as_button.setText(_("Save As"))
        self.record_button.setText(_("Record"))
        self.revert_button.setText(_("Revert"))
        self.label.setText(_("Insert text to play"))
        self.label_2.setText(_("Base settings"))
        self.play_button.setText(_("Play"))
        self.stop_button.setText(_("Stop"))
        self.label_3.setText(_("Language"))
        self.language_comboBox.setItemText(0, _("Hungarian"))
        self.language_comboBox.setItemText(1, _("English"))
        self.label_4.setText(_("Voice"))
        self.male_radioButton.setText(_("&Male"))
        self.female_radioButton.setText(_("Fe&male"))
        self.label_10.setText(_("Variant:"))
        self.label_5.setText(_("Advanced settings"))
        self.label_6.setText(_("Pitch:"))
        self.label_7.setText(_("Volume:"))
        self.label_8.setText(_("Speed:"))
        self.label_9.setText(_("Delay:"))
        self.menuFile.setTitle(_("F&ile"))
        self.menuEdit.setTitle(_("E&dit"))
        self.menuHelp.setTitle(_("He&lp"))
        self.actionExit.setText(_("&Exit"))
        self.actionExit.setShortcut(_("Ctrl+Q"))
        self.actionNew.setText(_("New"))
        self.actionNew.setShortcut(_("Ctrl+N"))
        self.actionOpen.setText(_("Open"))
        self.actionOpen.setShortcut(_("Ctrl+O"))
        self.actionSave_As.setText(_("Save As"))
        self.actionSave_As.setShortcut(_("Ctrl+S"))
        self.actionQuit.setText(_("Quit"))
        self.actionQuit.setShortcut(_("Ctrl+Q"))
        self.actionPlay.setText(_("Play"))
        self.actionPlay.setShortcut(_("Ctrl+P"))
        self.actionStop.setText(_("Stop"))
        self.actionStop.setShortcut(_("Ctrl+K"))
        self.actionRecord.setText(_("Record"))
        self.actionRecord.setShortcut(_("Ctrl+R"))
        self.actionRevert.setText(_("Revert"))
        self.actionRevert.setShortcut(_("Ctrl+Del"))
        self.actionAbout.setText(_("About"))

